protected/models/Manageaccounts.php
<?php

/**
 * This is the model class for table "{{manageaccounts}}".
 *
 * The followings are the available columns in table '{{manageaccounts}}':
 * @property integer $id
 * @property string $accountCode
 * @property string $accountLogin
 * @property string $accountSecret
 * @property string $accountName
 * @property string $createdAt
 * @property string $roleCode
 * @property string $accountEmail
 * @property string $phoneNumber
 * @property integer $activeStatus
 * @property string $accountSecretKey
 * @property string $lastLoginAt
 * @property string $lastLoginIn
 * @property integer $onLogin
 */
class Manageaccounts extends CActiveRecord
{

    public $roleName;
    public $accountReSecret;

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{manageaccounts}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('accountCode, accountLogin, accountSecret, roleCode', 'required'),
            array('activeStatus, onLogin', 'numerical', 'integerOnly' => true),
            array('accountCode, roleCode, lastLoginIn', 'length', 'max' => 20),
            array('accountLogin, accountSecret, accountEmail', 'length', 'max' => 100),
            array('accountName', 'length', 'max' => 120),
            array('phoneNumber', 'length', 'max' => 15),
            array('accountSecretKey', 'length', 'max' => 10),
            array('createdAt, lastLoginAt', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, accountCode, accountLogin, accountSecret, accountName, createdAt, roleCode, accountEmail, phoneNumber, activeStatus, accountSecretKey, lastLoginAt, lastLoginIn, onLogin', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'roles' => array(self::HAS_ONE, 'Roles', '', 'on' => 'roleCode = roles.roleCode'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'accountCode' => 'Mã tài khoản',
            'accountLogin' => 'Tài khoản',
            'accountSecret' => 'Mật khẩu',
            'accountReSecret' => 'Nhập lại mật khẩu',
            'accountName' => 'Tên đầy đủ',
            'createdAt' => 'Ngày tạo',
            'roleCode' => 'Quyền truy cập',
            'accountEmail' => 'Địa chỉ E-mail',
            'phoneNumber' => 'Số điện thoại',
            'activeStatus' => 'Trạng thái',
            'accountSecretKey' => 'Account Secret Key',
            'lastLoginAt' => 'Lần cuối đăng nhập lúc',
            'lastLoginIn' => 'Lần cuối đăng nhập tại',
            'onLogin' => 'Trạng thái đăng nhập',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('accountCode', $this->accountCode, true);
        $criteria->compare('accountLogin', $this->accountLogin, true);
        $criteria->compare('accountSecret', $this->accountSecret, true);
        $criteria->compare('accountName', $this->accountName, true);
        $criteria->compare('createdAt', $this->createdAt, true);
        $criteria->compare('roleCode', $this->roleCode, true);
        $criteria->compare('accountEmail', $this->accountEmail, true);
        $criteria->compare('phoneNumber', $this->phoneNumber, true);
        $criteria->compare('activeStatus', $this->activeStatus);
        $criteria->compare('accountSecretKey', $this->accountSecretKey, true);
        $criteria->compare('lastLoginAt', $this->lastLoginAt, true);
        $criteria->compare('lastLoginIn', $this->lastLoginIn, true);
        $criteria->compare('onLogin', $this->onLogin);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function validatePassword($password, $secretKey)
    {
        $function = new Functions;
        return $function->hashPassword($password, $secretKey) == $this->accountSecret;
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Manageaccounts the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function getAccountInfo($accountName, $fetch = false, $fetchName = "")
    {
        $model = new CDbCriteria;
        $model->select = "t.*, rl.roleName as roleName";
        $model->condition = "accountLogin = :acclogin";
        $model->params = array(":acclogin" => $accountName);
        $model->join = "INNER JOIN anc_roles rl ON rl.roleCode = t.roleCode";

        $findData = $this->model()->find($model);
        if(!empty($findData)){
            if ($fetch)
                return $findData->$fetchName;
            else
                return $findData;
        }else{
            return "";
        }

    }
}

protected/controllers/ManageaccountsController.php
<?php

class ManageaccountsController extends Controller
{
    private $function;
    /**
     *
     *
     */
    public function init()
    {
        parent::init();
        if (!isset(Yii::app()->session['loggedin'])) {
            $this->redirect(array("site/login"));
        }

        $this->pageTitle = "Quản lý tài khoản";
        $this->function = new Functions();
    }

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Manageaccounts;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Manageaccounts']))
		{
			$model->attributes=$_POST['Manageaccounts'];
            $secretKey = $this->function->generatesalt(10);
            $accountPass = $_POST['Manageaccounts']['accountSecret'];

            $hashSecret = $this->function->hashPassword($accountPass, $secretKey);

            $model->accountSecret = $hashSecret;
            $model->accountSecretKey = $secretKey;

			if($model->save()){
                echo json_encode(array('status' => true, 'msg' => 'Tạo tài khoản thành công. '));
            }else{
                echo json_encode(array('status' => false, 'msg' => 'Tạo tài khoản thất bại. Vui lòng kiểm tra lại toàn bộ thông tin.'));
            }

		}else{
            $this->render('create',array(
                'model'=>$model,
            ));
        }
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Manageaccounts']))
		{
			$model->attributes=$_POST['Manageaccounts'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Manageaccounts');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Manageaccounts('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Manageaccounts']))
			$model->attributes=$_GET['Manageaccounts'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Manageaccounts the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Manageaccounts::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Manageaccounts $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='manageaccounts-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

    public function actionCheckAccount(){
        $requestedAccount  = $_REQUEST['Manageaccounts']['accountLogin'];
        $findAccount = Manageaccounts::model()->find("accountLogin = :account", array(":account" => $requestedAccount));
        if(!empty($findAccount))
            echo "false";
        else
            echo "true";
    }

    public function actionGetAccCode(){
        $function = new Functions;
        $accCode = $function->generateTableCode("account");
        echo $accCode;
    }
}

protected/views/manageaccounts/_form.php
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'manageaccounts-form',
    'enableAjaxValidation'=>false,
    'htmlOptions' => array(
        'class' => 'form-horizontal'
    )
)); ?>
    <div id="add-accounts-alert" class="alert alert-warning fade in m-b-15" style="display: none;">
        <span class="alt-content">
            <strong>Warning!</strong>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </span>
        <span data-dismiss="alert" class="close">×</span>
    </div>
	<div class="form-group">
		<?php echo $form->labelEx($model,'accountCode', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-6">
            <?php echo $form->textField($model,'accountCode',array('class' => 'form-control accountCode', 'readonly' => 'readonly')); ?>
            <?php echo $form->error($model,'accountCode'); ?>
        </div>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'accountLogin', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php echo $form->textField($model,'accountLogin',array('class' => 'form-control')); ?>
            <?php echo $form->error($model,'accountLogin'); ?>
        </div>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'accountSecret', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php echo $form->passwordField($model,'accountSecret',array('class' => 'form-control')); ?>
            <?php echo $form->error($model,'accountSecret'); ?>
        </div>
	</div>

    <div class="form-group">
        <?php echo $form->labelEx($model,'accountReSecret', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php echo $form->passwordField($model,'accountReSecret',array('class' => 'form-control')); ?>
            <?php echo $form->error($model,'accountReSecret'); ?>
        </div>
    </div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'accountName', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php echo $form->textField($model,'accountName',array('class' => 'form-control')); ?>
            <?php echo $form->error($model,'accountName'); ?>
        </div>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'roleCode', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php //if(Yii::app()->user->roles == "administrator"): ?>
                <?php $listroles = CHtml::listData(Roles::model()->findAll(), 'roleCode','roleName');?>
            <?php //else: ?>
                <?php //$listroles = CHtml::listData(Roles::model()->findAll("roleName != :name", array(":name" => 'administrator')), 'roleCode','roleName');?>
            <?php //endif; ?>
            <?php echo $form->dropDownList($model,'roleCode', $listroles, array('class' => 'form-control', 'empty' => 'Chọn quyền truy cập')); ?>
            <?php echo $form->error($model,'roleCode'); ?>
        </div>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'accountEmail', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php echo $form->textField($model,'accountEmail',array('class' => 'form-control')); ?>
            <?php echo $form->error($model,'accountEmail'); ?>
        </div>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'phoneNumber', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9">
            <?php echo $form->textField($model,'phoneNumber',array('class' => 'form-control')); ?>
            <?php echo $form->error($model,'phoneNumber'); ?>
        </div>
	</div>

	<div class="form-group">
        <label class="col-md-3 control-label"></label>
        <div class="col-md-9">
            <?php echo CHtml::submitButton($model->isNewRecord ? 'Tạo tài khoản' : 'Cập nhật tài khoản', array('class' => 'btn btn-success')); ?>
        </div>
	</div>

<?php $this->endWidget(); ?>

protected/views/manageaccounts/_search.php
<?php
/* @var $this ManageaccountsController */
/* @var $model Manageaccounts */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'accountCode'); ?>
		<?php echo $form->textField($model,'accountCode',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'accountLogin'); ?>
		<?php echo $form->textField($model,'accountLogin',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'accountSecret'); ?>
		<?php echo $form->textField($model,'accountSecret',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'accountName'); ?>
		<?php echo $form->textField($model,'accountName',array('size'=>60,'maxlength'=>120)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'createdAt'); ?>
		<?php echo $form->textField($model,'createdAt'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'roleCode'); ?>
		<?php echo $form->textField($model,'roleCode',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'accountEmail'); ?>
		<?php echo $form->textField($model,'accountEmail',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'phoneNumber'); ?>
		<?php echo $form->textField($model,'phoneNumber',array('size'=>15,'maxlength'=>15)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'activeStatus'); ?>
		<?php echo $form->textField($model,'activeStatus'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'accountSecretKey'); ?>
		<?php echo $form->textField($model,'accountSecretKey',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lastLoginAt'); ?>
		<?php echo $form->textField($model,'lastLoginAt'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lastLoginIn'); ?>
		<?php echo $form->textField($model,'lastLoginIn',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'onLogin'); ?>
		<?php echo $form->textField($model,'onLogin'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/manageaccounts/_view.php
<?php
/* @var $this ManageaccountsController */
/* @var $data Manageaccounts */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('accountCode')); ?>:</b>
	<?php echo CHtml::encode($data->accountCode); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('accountLogin')); ?>:</b>
	<?php echo CHtml::encode($data->accountLogin); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('accountSecret')); ?>:</b>
	<?php echo CHtml::encode($data->accountSecret); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('accountName')); ?>:</b>
	<?php echo CHtml::encode($data->accountName); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('createdAt')); ?>:</b>
	<?php echo CHtml::encode($data->createdAt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('roleCode')); ?>:</b>
	<?php echo CHtml::encode($data->roleCode); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('accountEmail')); ?>:</b>
	<?php echo CHtml::encode($data->accountEmail); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('phoneNumber')); ?>:</b>
	<?php echo CHtml::encode($data->phoneNumber); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('activeStatus')); ?>:</b>
	<?php echo CHtml::encode($data->activeStatus); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('accountSecretKey')); ?>:</b>
	<?php echo CHtml::encode($data->accountSecretKey); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('lastLoginAt')); ?>:</b>
	<?php echo CHtml::encode($data->lastLoginAt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('lastLoginIn')); ?>:</b>
	<?php echo CHtml::encode($data->lastLoginIn); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('onLogin')); ?>:</b>
	<?php echo CHtml::encode($data->onLogin); ?>
	<br />

	*/ ?>

</div>

protected/views/manageaccounts/admin.php
<?php
/* @var $this ManageaccountsController */
/* @var $model Manageaccounts */

$this->breadcrumbs=array(
	'Manageaccounts'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Manageaccounts', 'url'=>array('index')),
	array('label'=>'Create Manageaccounts', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#manageaccounts-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->
<div class="row">
    <div class="col-md-12 ui-sortable">
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <h4 class="panel-title"><?php echo $this->pageTitle; ?></h4>
            </div>
            <div class="panel-body" style="display: block;">
                <?php echo CHtml::link('Thêm tài khoản', array('manageaccounts/create'), array('class' => 'btn btn-primary btn-addcate')); ?>
                <?php $this->widget('zii.widgets.grid.CGridView', array(
                    'id'=>'manageaccounts-grid',
                    'itemsCssClass' => 'table table-striped table-bordered dataTable no-footer',
                    'summaryText' => 'Hiển thị danh sách từ {start}-{end} trong tổng số {count} kết quả',
                    'dataProvider'=>$model->search(),
                    'filter'=>$model,
                    'columns'=>array(
                        array(
                            'id' => 'autoId',
                            'class' => 'CCheckBoxColumn',
                            'selectableRows' => '50',
                        ),
                        'accountCode',
                        'accountLogin',
                        'accountName',
                        'createdAt',
                        array(
                            'name' => 'roleCode',
                            //'type' => 'raw',
                            'value' => 'Manageaccounts::model()->getAccountInfo($data->accountLogin, true, "roleName")' //'$data->roles->roleName'
                        ),
                        'lastLoginAt',
                        'lastLoginIn',
                        /*
                        'accountEmail',
                        'phoneNumber',
                        'activeStatus',
                        'accountSecretKey',
                        'lastLoginIn',
                        'onLogin',
                        */
                        array(
                            'class'=>'CButtonColumn',
                            'template' => '{update}'
                        ),
                    ),
                )); ?>
            </div>
        </div>
    </div>
</div>

protected/views/manageaccounts/create.php
<?php
/* @var $this ManageaccountsController */
/* @var $model Manageaccounts */

$this->breadcrumbs=array(
	'Manageaccounts'=>array('index'),
	'Create',
);
?>
<div class="row">
    <div class="col-md-12 ui-sortable">
        <div class="panel panel-inverse">
            <div class="panel-heading">

            </div>
            <div class="panel-body" style="display: block">
                <?php $this->renderPartial('_form', array('model'=>$model)); ?>
            </div>
        </div>
    </div>
</div>
<?php
$function = new Functions;
$accCode = $function->generateTableCode("account");

Yii::app()->clientScript->registerScript('createAccounts', "
	var accCodetime = '".$accCode."';

	$('.accountCode').val(accCodetime);

    $('.books-quantity').change(function(){
        var _bookImportprice = $('.book-import-price').val();
        var _bookQuantity = $(this).val();

        var _totalAmount = _bookImportprice * _bookQuantity;
        console.log(_bookImportprice * _bookQuantity);

        $('.book-total-amount').val(_totalAmount);
    });
	/**  Validate books form. */
	$('#manageaccounts-form').validate({
                onfocusout: true,
                onkeyup: true,
                onclick: true,
                focusInvalid: true,
                debug:true,
                rules:{
                    'Manageaccounts[accountLogin]': {required: true, remote:{url: '".Yii::app()->createUrl('manageaccounts/checkaccount')."', type: 'post'}},
                    'Manageaccounts[accountSecret]': {required: true, minlength: 6},
                    'Manageaccounts[accountReSecret]': {equalTo: '#Manageaccounts_accountSecret'},
                    'Manageaccounts[roleCode]': 'required'
                },
                messages:{
                    'Manageaccounts[accountLogin]': {required: 'Vui lòng nhập tên tài khoản đầy đủ.', remote: 'Tài khoản đã tồn tại. Vui lòng chọn tài khoản khác'},
                    'Manageaccounts[accountSecret]': {required: 'Vui lòng nhập mật khẩu. ', minlength: 'Mật khẩu tối thiểu chứa 6 ký tự'},
                    'Manageaccounts[accountReSecret]': {equalTo: 'Mật khẩu nhập lại không khớp. Vui lòng kiểm tra lại.'},
                    'Manageaccounts[roleCode]': 'Chưa chọn quyền truy cập. Vui lòng chọn.'
                },
                submitHandler: function(){
                    var formData = new FormData($('#manageaccounts-form')[0]);
                    var action = $('#manageaccounts-form').attr('action');

                       $.ajax({
                            url: action,
                            type: 'POST',
                            data: formData,
                            async: false,
                            success: function (data) {
                                var obj = jQuery.parseJSON(data);
                                if(obj.status){
                                    $('.alt-content').html(obj.msg);
                                    $('#add-accounts-alert').removeAttr('style');
                                    $('#add-accounts-alert').removeClass('alert-warning');
                                    $('#add-accounts-alert').addClass('alert-success');
                                    $('#manageaccounts-form')[0].reset();

                                    setTimeout(function(){ $('#add-accounts-alert').fadeOut() }, 5000);

                                    $.get('".Yii::app()->createUrl('manageaccounts/getacccode')."', {}, function(returncode){
                                        $('#Manageaccounts_accountCode').val(returncode);
                                    });

                                }else{
                                    $('.alt-content').html(obj.msg);
                                    $('#add-accounts-alert').removeClass('alert-success');
                                    $('#add-accounts-alert').addClass('alert-warning');
                                    $('#add-accounts-alert').removeAttr('style');
                                }
                            },
                            cache: false,
                            contentType: false,
                            processData: false
                        });
                }
            });
");
?>

protected/views/manageaccounts/index.php
<?php
/* @var $this ManageaccountsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Manageaccounts',
);

$this->menu=array(
	array('label'=>'Create Manageaccounts', 'url'=>array('create')),
	array('label'=>'Manage Manageaccounts', 'url'=>array('admin')),
);
?>

<h1>Manageaccounts</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/manageaccounts/update.php
<?php
/* @var $this ManageaccountsController */
/* @var $model Manageaccounts */

$this->breadcrumbs=array(
	'Manageaccounts'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Manageaccounts', 'url'=>array('index')),
	array('label'=>'Create Manageaccounts', 'url'=>array('create')),
	array('label'=>'View Manageaccounts', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Manageaccounts', 'url'=>array('admin')),
);
?>

<h1>Update Manageaccounts <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/manageaccounts/view.php
<?php
/* @var $this ManageaccountsController */
/* @var $model Manageaccounts */

$this->breadcrumbs=array(
	'Manageaccounts'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Manageaccounts', 'url'=>array('index')),
	array('label'=>'Create Manageaccounts', 'url'=>array('create')),
	array('label'=>'Update Manageaccounts', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Manageaccounts', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Manageaccounts', 'url'=>array('admin')),
);
?>

<h1>View Manageaccounts #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'accountCode',
		'accountLogin',
		'accountSecret',
		'accountName',
		'createdAt',
		'roleCode',
		'accountEmail',
		'phoneNumber',
		'activeStatus',
		'accountSecretKey',
		'lastLoginAt',
		'lastLoginIn',
		'onLogin',
	),
)); ?>